### ISSUE TITLE
IMPORTANT 

### ISSUE THREAD

**Issue by LaganYT** [alexwohlbruck/jukebox#17]
Please continue development this was an awesome project until it became ignored.

**Comment by LaganYT** [comment]
Oh also, it says project error when visiting the website.

**Comment by alexwohlbruck** [comment]
I'd love to finish it but I've got a full time job and responsibilities now !

**Comment by alexwohlbruck** [comment]
I might pick it up one day if I get some more spare time

**Comment by LaganYT** [comment]
Alright! I hope your life is well and you one day have time to work on this project again. I would love to help but first I need to gain some more knowledge on this language. Anyways have a good day.
