### ISSUE TITLE
Heroku app not loading

### ISSUE THREAD

**Issue by LaganYT** [alexwohlbruck/jukebox#18]
![image](https://github.com/alexwohlbruck/jukebox/assets/95306463/e586bd31-2e58-4314-9b99-e325cd5e216b)

**Comment by alexwohlbruck** [comment]
should be up again

**Comment by LaganYT** [comment]
Nope, still has an application error

**Comment by alexwohlbruck** [comment]
which endpoint are you accessing?

**Comment by LaganYT** [comment]
https://jukebox-redux.herokuapp.com/

**Comment by alexwohlbruck** [comment]
oh, I thought you were referring to cat facts, my bad.
I haven't really been maintaining that app, but I'll restart the server and
see if that fixes

**Comment by LaganYT** [comment]
it has not been fixed

**Comment by LaganYT** [comment]
Seems to be a heroku issue, when I began hosting it on glitch everything worked again.
