### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LaganYT** [alexwohlbruck/jukebox#20]
Which part of the code makes the songs synchronized?

**Comment by alexwohlbruck** [comment]
Try https://github.com/alexwohlbruck/jukebox/blob/develop/app/sockets/player.socket.js

To be honest the sync feature isn't great, it tries to rely on a computation of the socket connection latency to offset the "play" event for different clients. There is also no sessions support, so all playback events are global. Feel free to experiment with it though!

**Comment by LaganYT** [comment]
Ok, I will look at it. I am trying to get everything running again by building the missing code from the ground up. Hoping that I can get it to work since I barely know what I'm doing lol

**Comment by alexwohlbruck** [comment]
go ahead and clone it and mess around! can't hurt

**Comment by LaganYT** [comment]
That's what I've been doing. Trying to get this thing up and running again.
