### ISSUE TITLE
Will this be worked on again?

### ISSUE THREAD

**Issue by LaganYT** [alexwohlbruck/jukebox#5]
The title says it all.

**Comment by alexwohlbruck** [comment]
Possibly! What would you like to see done?

**Comment by LaganYT** [comment]
Yes i use this as my main provider for music! Also is it fine if i use it in my website?

**Comment by alexwohlbruck** [comment]
Sure that's fine. Keep in mind that the music that streams from the API is copyrighted so know that if you are monetizing your website.

**Comment by LaganYT** [comment]
I am not monetizing the website just letting anyone listen to music for free.
